const PRODUCTS_KEY='vyro_products',CART_KEY='vyro_cart',USER_KEY='vyro_user',ORDERS_KEY='vyro_orders';
const defaults=[{id:1,name:'Shadow Logo Tee',category:'basic',price:450,stock:12,active:true},{id:2,name:'VYRO Oversize',category:'oversize',price:590,stock:8,active:true},{id:3,name:'Signal Heavy Tee',category:'basic',price:520,stock:15,active:true},{id:4,name:'Concrete Oversize',category:'oversize',price:650,stock:6,active:true},{id:5,name:'Core Black',category:'basic',price:425,stock:20,active:true},{id:6,name:'After Dark',category:'oversize',price:620,stock:0,active:true}];
let products=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'null')||defaults,cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]'),filter='all';
const $=id=>document.getElementById(id),money=n=>`${Number(n).toLocaleString('ar-EG')} ج.م`,saveCart=()=>localStorage.setItem(CART_KEY,JSON.stringify(cart));
function renderProducts(){const list=products.filter(p=>p.active!==false&&(filter==='all'||p.category===filter));$('productGrid').innerHTML=list.map(p=>`<article class="product ${p.stock<1?'soldout':''}"><div class="product-img"><div class="placeholder">VYRO<br>${p.category==='oversize'?'OVR':'CORE'}</div></div><div class="product-info"><h3>${p.name}</h3><div class="product-meta"><span>${money(p.price)}</span><span>${p.stock?'متاح':'نفد'}</span></div></div>${p.stock?`<button class="add-btn" onclick="addToCart(${p.id})" aria-label="أضف للسلة">+</button>`:''}</article>`).join('')||'<p class="muted">لا توجد منتجات في هذا التصنيف.</p>'}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||!p.stock)return;const item=cart.find(x=>x.id===id);if(item){if(item.qty<p.stock)item.qty++}else cart.push({id,qty:1});saveCart();renderCart();toggleCart(true)}
function renderCart(){let total=0,count=0;const box=$('cartItems');if(!cart.length)box.innerHTML='<p class="muted">السلة فاضية حاليًا.<br>أضف قطعة تعجبك.</p>';else box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return '';total+=p.price*i.qty;count+=i.qty;return `<div class="cart-item"><div><h4>${p.name}</h4><small>${money(p.price)} × ${i.qty}</small></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div>`}).join('');$('cartCount').textContent=count;$('cartTotal').textContent=money(total)}
function changeQty(id,d){const i=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);if(p&&i.qty>p.stock)i.qty=p.stock;saveCart();renderCart()}
function toggleCart(force){const open=force===true||!$('cart').classList.contains('open');$('cart').classList.toggle('open',open);$('overlay').classList.toggle('open',open)}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')}function closeAuth(){$('authModal').classList.remove('open')}function closeOrderForm(){$('orderModal').classList.remove('open')}
function currentUser(){return JSON.parse(localStorage.getItem(USER_KEY)||'null')}
$('accountBtn').onclick=()=>{const u=currentUser();if(u){alert(`أهلًا ${u.name}! طلباتك محفوظة في حسابك ويمكن للإدارة رؤيتها.`)}else openModal('authModal')};
$('authForm').onsubmit=e=>{e.preventDefault();const u={name:$('authName').value.trim(),email:$('authEmail').value.trim(),createdAt:new Date().toISOString()};localStorage.setItem(USER_KEY,JSON.stringify(u));$('authMessage').textContent='تم إنشاء الحساب، تقدر تكمل طلبك الآن.';setTimeout(()=>{closeAuth();if(cart.length)openModal('orderModal')},500)};
function checkout(){if(!cart.length)return alert('أضف منتجًا للسلة أولًا.');const u=currentUser();if(!u){$('authMessage').textContent='لازم تعمل حساب قبل إتمام الشراء.';openModal('authModal');return}$('signedInAs').textContent=`مسجل الدخول باسم ${u.name}`;openModal('orderModal')}
$('orderForm').onsubmit=e=>{e.preventDefault();const u=currentUser();const order={id:'VY-'+Date.now().toString().slice(-6),user:u,phone:$('customerPhone').value.trim(),address:$('customerAddress').value.trim(),items:cart,total:cart.reduce((s,i)=>s+(products.find(p=>p.id===i.id)?.price||0)*i.qty,0),status:'جديد',createdAt:new Date().toISOString()};const orders=JSON.parse(localStorage.getItem(ORDERS_KEY)||'[]');orders.unshift(order);localStorage.setItem(ORDERS_KEY,JSON.stringify(orders));cart=[];saveCart();renderCart();$('orderMessage').textContent=`تم تأكيد طلبك ${order.id} بنجاح!`;setTimeout(()=>{closeOrderForm();toggleCart(false);$('orderForm').reset()},1300)};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderProducts()});renderProducts();renderCart();
